services:
  server:
    build: ./Dockerfile.dev
    image: server
    volumes: # only for dev hot reload, not need in production
      - /code/node_modules
      - .:/code:cached
    ports: # not need if use nginx
      - 80:5555
    # stdin_open: true # `docker run -i`
    # tty: true # `docker run -t`
